#version 460 core

layout(local_size_x = 1024) in;

layout(std430, binding = 0) readonly buffer block0
{
    vec3 in_oldPosition[];
};

layout(std430, binding = 1) readonly buffer block1
{
    vec3 in_newPosition[];
};

layout(std430, binding = 2) writeonly buffer block2
{
    vec3 out_velocities[];
};

uniform float u_deltaTime;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    out_velocities[id] = (in_newPosition[id] - in_oldPosition[id]) / u_deltaTime;
}
