#version 460 core

layout(local_size_x = 1024) in;

layout(std430, binding = 0) coherent buffer block0
{
    uint inout_sumParticlesCells[];
};

uniform uint u_step;

void main()
{
    uint globalId = gl_GlobalInvocationID.x;
    uint mask = (1 << u_step) - 1;
    uint readId = ((globalId >> u_step) << (u_step + 1)) + mask;
    uint writeId = readId + 1 + (globalId & mask);
    atomicAdd(inout_sumParticlesCells[writeId], inout_sumParticlesCells[readId]);
}